require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '254785450636',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'off',
    ADM: process.env.ANTIDELETE || 'on',
    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
   ALIVE_URL: process.env.ALIVE_URL,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiaUFzam1HdkZOOFFtRGxOeisxc0laaEhqcktDd0NWUHdmWEM5U2ZJd0Ezcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicnBHZEVjbUVyZENLaFNReXNKOUQ5dVlMZHhIeHZFTTdxNmRiS1kvYy9oND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnUExhZW9rTnZIODROYUNpUkVZUE5HZFpHYXdXa0w4OGNoY2lEYWo5WjJJPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZTXdWTzQ0Qnk3c3VPL1lyNlBUWTBxTXQzSUVzZkRwZTBMelFadUtwVDA0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjBLdkdjeTRGTjhqL1JZOGtGeTlTT2JwOTkrNGU4ZWtLaDZYRVkwQ2pwRlE9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkVKK01PWmE2NnByZnhWWFhkZi9XU21sSkMzbHJWcVFNWFA0Nis1SzF4RFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMkdjaGJ6SnNHcXJFampOa1dCbm02c3h0allLNXZ0UmdSMjdXQkY2eHRXdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiT29SSGNjOWRZM292WDNYL0d1MC94eHhtelJBaUxEam1IS3BkeERoYWxsWT0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IktYUEo4TFlTSjVKTG1aT0xaRVhBMnQ0K3Z4ak1YMG1BYlZYaDBuT0x4Ni9JaDdTSDBZaEk1MHZNVUNKbklYYjZzdk8rU0VyVVo3bCtXMlYrcWpEQkRBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6NTQsImFkdlNlY3JldEtleSI6IjdqcTVqdGtxQ0JtMUZYZ2dtMkR5bVR2WUtSQzlhOFo3ZEJ0M2t6blYvNXM9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjU0Nzg1NDUwNjM2QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjQ0OEMwRjJFNUI0NTBDOUM3NjNFQkI5QjU4QjMzNzBDIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTIwMzYzOTZ9LHsia2V5Ijp7InJlbW90ZUppZCI6IjI1NDc4NTQ1MDYzNkBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIyQTAxOTZBNDUyNzkyMDZCMTY3RkNENDc3NzI2MDI1RCJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUyMDM2Mzk2fV0sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJSTEM4U1IzNiIsIm1lIjp7ImlkIjoiMjU0Nzg1NDUwNjM2OjZAcy53aGF0c2FwcC5uZXQiLCJuYW1lIjoib2tvdGhyZWFnYW43NzkiLCJsaWQiOiIxNzE5OTI1NTI2MDc4MDQ6NkBsaWQifSwiYWNjb3VudCI6eyJkZXRhaWxzIjoiQ096U3o4OERFSnpvdDhNR0dBRWdBQ2dBIiwiYWNjb3VudFNpZ25hdHVyZUtleSI6InNKb3JzUDM5TGpLODNqSnExV1crL2o4bkEvNHhVVk5GNFFxOU5nNXUzSFU9IiwiYWNjb3VudFNpZ25hdHVyZSI6IlZ4aWluTWNXRXAwRkNVMjdwQU9hSUlVNlhNQTJGRDhraWlXVkFuSW1YSXhLcXNTUTVJSTF2VFllZDFpbHJHaDREK2tPOHRKVlpSd2hKbHRJc1RJNEJnPT0iLCJkZXZpY2VTaWduYXR1cmUiOiJiTTVVWit0d0FZbi9sYTJKQkovdnRMcldJYjlKQ3VUTzJJSzJFYThpRThoa0JCWnRVTGpqdzJZTGZ3a3VIMXQ5c3IrT1Y2dFo3WFh2cm5KZ1phRFRDdz09In0sInNpZ25hbElkZW50aXRpZXMiOlt7ImlkZW50aWZpZXIiOnsibmFtZSI6IjI1NDc4NTQ1MDYzNjo2QHMud2hhdHNhcHAubmV0IiwiZGV2aWNlSWQiOjB9LCJpZGVudGlmaWVyS2V5Ijp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQmJDYUs3RDkvUzR5dk40eWF0Vmx2djQvSndQK01WRlRSZUVLdlRZT2J0eDEifX1dLCJwbGF0Zm9ybSI6InNtYmEiLCJyb3V0aW5nSW5mbyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkNCSUlDQT09In0sImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcCI6MTc1MjAzNjM5NCwibGFzdFByb3BIYXNoIjoiMlY3N3FVIiwibXlBcHBTdGF0ZUtleUlkIjoiQUFBQUFHUnUifQ==',
    timezone: 'Africa/Nairobi',
    USER_LID: process.env.YOUR_LID || null,
    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
