require('dotenv').config();

function mapPresence(val) {
    const mapping = {
        typing: 'composing',
        online: 'available',
        recording: 'recording',
        paused: 'paused',
        offline: 'unavailable'
    };
    return mapping[val?.toLowerCase()?.trim()] || 'paused';
}

module.exports = {
    prefixes: process.env.PREFIX
        ? process.env.PREFIX.split(',').map(p => p.trim())
        : [''],

    NUMBER: process.env.YOUR_NUMBER || '233538733413',
    MODE: (process.env.MODE || 'private').toLowerCase().trim(),
    WARN_LIMIT: process.env.WARNINGS || '3',
    ON: process.env.YOUR_NAME || 'FLASH-MD',
    ANTICALL: process.env.ANTICALL || 'on',
    ADM: process.env.ANTIDELETE || 'on',
    AUTO_VIEW_STATUS: process.env.AUTO_READ_STATUS === 'on',
    AUTO_LIKE: process.env.AUTO_LIKE === 'on',
    AUTO_READ_MESSAGES: process.env.AUTO_READ_DM === 'on',
    HEROKU_API_KEY: process.env.HEROKU_API_KEY,
    HEROKU_APP_NAME: process.env.HEROKU_APP_NAME,
   ALIVE_URL: process.env.ALIVE_URL,
    sessionBase64: process.env.SESSION || 'eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ1BxaU1QdmVnWVZuZFRyOEhhSkRZR3NyQkdtOURoUUlhdlpHVUQ4UkxWcz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicDh1QkxwOHkyTGtjVS9yWVIxbWxPUEZENld4NXd1OVVXWWNub3pTYkd5OD0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJZQXV1SHFGY2lBWFVGUUFWSXdTVmYwc2JjZm9qU09UeWd2RHhSc2Nrdmx3PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJjUUtuWStlMXo0SjdTTi9vWllFQWU4RDQ1V1g4bTNBTjkxVVlvSFM1WUVvPSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InFBZjN6cU9UODBURk4xYVUwMUYwWmhPb0RNZEtCUkZtMllTbENjcCtRMms9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6InhFQWRuSFBOdU5abGVUZ25pUmlCU2hVK0g4cG9zSm9DdGdMY1A5bWNFakU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiZU8wL2hrWlFsdVJjc0JMdnhoV2c5em5MN3ROL3orcXZ4bDFOMU1YcE1rQT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiSkFpK0lZaGpib1VoczF1UVhKcjlIOE1KbzZ2ZEFESVUvN0VjVkVHbWdIOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IlNZbTBUSEJzSXVnSFJEQXFrRlFWWTRWc0lDck1pclg1K3FSVTcwNGtCc3lSUW9aK0pFR0R0NnNBR1FBdEJGUnZKWVJBRDd4ZnJsMVRUREd2YURrS2dRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTMsImFkdlNlY3JldEtleSI6ImFmc3VSRWd0T2ZoWllReXoxWm5vUXN4cm05VmZudWZDaG85dmQ1VDZhQ3M9IiwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzIjpbeyJrZXkiOnsicmVtb3RlSmlkIjoiMjMzNTM4NzMzNDEzQHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjlBMDlEOEQyNkE3RTgxMzNBN0U1NTlGQzZFN0NBQUZGIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTEwMzkwNDl9LHsia2V5Ijp7InJlbW90ZUppZCI6IjIzMzUzODczMzQxM0BzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzQkUyNEJBMzcwNzIyNTNCRjNCMDk3QTY1RDE5NzU0MSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUxMDM5MDU2fV0sIm5leHRQcmVLZXlJZCI6NDMsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjo0MywiYWNjb3VudFN5bmNDb3VudGVyIjoxLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJZQ1EzVlgxRyIsIm1lIjp7ImlkIjoiMjMzNTM4NzMzNDEzOjEzQHMud2hhdHNhcHAubmV0IiwibmFtZSI6IvCdlo4g8J2WhvCdlpIg8J2WkPCdlo3wnZaG8J2WlPCdlpgiLCJsaWQiOiIxMTQzMTk3OTg4NzgyNDA6MTNAbGlkIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNKN3c1TzhFRUt6NCtzSUdHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJuQWV0SkVKanNnTUQ4ZnJmbVUvM0tUYzlrUkoxelY1djVHUTU0SEU0QXhFPSIsImFjY291bnRTaWduYXR1cmUiOiJFMXJ3RTN5WUhWK0ZBS3NtSVA4VmVkQWoxRUFqeFBGTm1TWk5TbWdXdVFaVjI0SEdlOFFGT3hsT3JmYUVTNlh4OEVLaUwrK3h5bXlJWUowaG43WnpDQT09IiwiZGV2aWNlU2lnbmF0dXJlIjoiRWxHaTlXZnN1eWZXbEpjSmU3VEpBZ3F1Tm1LM2RmS2pnN0V2QWVHTHZBa3FMMFFZbHVISDhNdisyS1hYVnBLZHJtek9IMk5EV3lpcDQ0NE94QlJ5Z1E9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMzM1Mzg3MzM0MTM6MTNAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWndIclNSQ1k3SURBL0g2MzVsUDl5azNQWkVTZGMxZWIrUmtPZUJ4T0FNUiJ9fV0sInBsYXRmb3JtIjoic21iYSIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0EwSUFnPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzUxMDM5MDM1LCJsYXN0UHJvcEhhc2giOiIzZ1BVSmsiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQUcydSJ9',
    timezone: 'Africa/Nairobi',
    USER_LID: process.env.YOUR_LID || 11431979887824013,
    PRESENCE_DM: mapPresence(process.env.PRESENCE_DM || 'typing'),
    PRESENCE_GROUP: mapPresence(process.env.PRESENCE_GROUP || 'recording'),

    mapPresence
};
